# Generated by Django 3.0.4 on 2020-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200322_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoelement',
            name='photo',
            field=models.ImageField(default=0, upload_to='myPictures'),
            preserve_default=False,
        ),
    ]
